#!/usr/bin/env bash

RED='\033[1;31m' # Bold red
NC='\033[0m' # No Color

if ! [ -x "$(command -v xygeni)" ]
then
    echo -e "${RED}Xygeni scanner could not be found.${NC} Please make sure Xygeni is installed properly.\nDocumentation can be found here: https://docs.xygeni.io/scanner/xygeni_scanner.html#_installation"
    exit 1
fi
#pwd
#ls -laR /home/ubuntu/LGV/precommit
# Configure the scan to fail when at least one critical issue found
#xygeni secrets -d /home/ubuntu/LGV/precommit --all-files --fail-on="critical"
#xygeni -q secrets -d . --staged-files --fail-on=high --no-stdin --format text --output ./.secrets.txt
xygeni -q secrets -d . --staged-files --fail-on=high --format text --output ./.secrets.txt
EXIT_CODE=$?

if [[ $EXIT_CODE -gt 127 ]]; then
  echo -e "${RED}Secrets found !${NC} Please remove them before commiting changes."
  cat ./.secrets.txt
elif [[ $EXIT_CODE -ne 0 ]]; then
  echo -e "${RED}Xygeni scan failed.${NC} Please contact your Xygeni administrator."
  echo -e "Log files can be found in ${GRAY}logs/noproject/secrets_noproject.log${NC}"
fi

# Cleanup and tell the git commit to stop (not 0) or continue (0)
rm -f ./.secrets.txt >/dev/null 2>&1
exit $EXIT_CODE

# Alternatively, do a partial scan
# xygeni scan --fail-on="severity:critical" \
#   --run=secrets,misconf,iac,compliance

# Any command could be used, like secrets, compliance, etc.
# xygeni secrets --fail-on="severity:critical"
