# This is a basic workflow to help you get started with Actions

name: Scanner on pull request (CMD)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push: #branch github.ref
  #  branches: [ "main" ]
  pull_request: #branch github.head_ref
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  XY_USERNAME: ${{ secrets.XY_USERNAME }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD }}
  XY_URL: ${{ secrets.XY_URL }}
  XY_PRJ_NAME: GH-${{ github.event.repository.name }}-CMD


# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'

      # Runs a single command using the runners shell
      - name: Git Log
        run: git log
        
      # Runs a single command using the runners shell
      - name: Cat npmrc
        run: cat ./src/.npmrc

      # Runs a set of commands using the runners shell 
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u ${{ env.XY_USERNAME }} -p ${{ env.XY_PASSWORD }} -s ${{ env.XY_URL }} -d ${GITHUB_WORKSPACE}/scanner 
          


      # Runs a set of commands using the runners shell
      # ${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail -n ${{ env.XY_PRJ_NAME }} --dir ${GITHUB_WORKSPACE} -e **/scanner/**
      # ${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail -n ${{ env.XY_PRJ_NAME }}${{ github.head_ref }} --dir ${GITHUB_WORKSPACE} -e **/scanner/**
      - name: Execution Xygeni Scanner (vuln)
        run: |
          echo Executing Xygeni scan ....    
          ${GITHUB_WORKSPACE}/scanner/xygeni secrets -u -d . --all-files --fail-on=high --no-stdin 
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
